// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZjVm4zvcS-u7qXQLpwa4DFoWwRe-vnaQ',
    appId: '1:758821895593:web:bf5f93679603577ef418b8',
    messagingSenderId: '758821895593',
    projectId: 'minorproj-8797d',
    authDomain: 'minorproj-8797d.firebaseapp.com',
    storageBucket: 'minorproj-8797d.appspot.com',
    measurementId: 'G-ZK6HEL3PMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6r8IZDGUgbqF-dw0sRbjFTQKPpQGbgG0',
    appId: '1:758821895593:android:9c4ec21487b4c4edf418b8',
    messagingSenderId: '758821895593',
    projectId: 'minorproj-8797d',
    storageBucket: 'minorproj-8797d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByCV5vM2LUCVnwOe5Axw4YeMB_Cl7Go68',
    appId: '1:758821895593:ios:e97ff0df77a2520df418b8',
    messagingSenderId: '758821895593',
    projectId: 'minorproj-8797d',
    storageBucket: 'minorproj-8797d.appspot.com',
    iosBundleId: 'com.example.learnifyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByCV5vM2LUCVnwOe5Axw4YeMB_Cl7Go68',
    appId: '1:758821895593:ios:85b563c2011be2bef418b8',
    messagingSenderId: '758821895593',
    projectId: 'minorproj-8797d',
    storageBucket: 'minorproj-8797d.appspot.com',
    iosBundleId: 'com.example.learnifyTask.RunnerTests',
  );
}
